install:
    - gem install bundler
    - bundle --version
    - bundle install
language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - 2.2.3
  - 2.3.0
  - 2.4.2
  - 2.5.0
  - jruby-19mode
  - jruby-9.0.1.0
  - rbx-19mode
